name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
        source-url: https://nuget.pkg.github.com/lifetime/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Test with dotnet
      run: dotnet test --configuration Release
    - name: Push to GitHub Package
      if: github.ref == 'refs/heads/main'
      run: dotnet nuget push "LifeTime/bin/Release/net5.0/LifeTime.*.nupkg" --skip-duplicate